/**
 * @file    sonar_lut.h
 * @brief   Waveform Lookup Table (LUT) interface for STM32G4 Sonar Transmitter.
 * @note    Encapsulates the precomputed chirp headers generated by src/export_c.py.
 *          Provides clean accessors for DMA streaming without duplicate symbol errors.
 */

#ifndef SONAR_LUT_H_
#define SONAR_LUT_H_

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Guard against redefinition if sonar_profiles.h is already included */
#ifndef SONAR_PROFILES_H_
/**
 * @brief Canonical transmission profile identifiers strictly aligned with SIH PS 26058.
 */
typedef enum {
    SONAR_PROFILE_LOW_FREQUENCY  = 0, /**< 100-220 kHz (f_c=160 kHz, B=120 kHz) for degraded/scattering channels */
    SONAR_PROFILE_BALANCED       = 1, /**< 200-400 kHz (f_c=300 kHz, B=200 kHz) nominal default (highest resolution) */
    SONAR_PROFILE_HIGH_FREQUENCY = 2, /**< 350-500 kHz (f_c=425 kHz, B=150 kHz) for narrow beam directivity */
    SONAR_PROFILE_COUNT          = 3
} SonarProfileId_t;

/**
 * @brief Descriptor structure storing metadata and Flash pointers for each profile.
 */
typedef struct {
    SonarProfileId_t profile_id;      /**< Profile enumeration */
    const char*      name;            /**< Human-readable descriptive name */
    uint32_t         sample_rate_hz;  /**< Sample rate (4,000,000 Hz) */
    uint32_t         f_start_hz;      /**< Chirp start frequency in Hz */
    uint32_t         f_end_hz;        /**< Chirp end frequency in Hz */
    uint32_t         duration_us;     /**< Pulse duration in microseconds (2000 us) */
    uint16_t         sample_count;    /**< Number of 16-bit samples (8000) */
    uint16_t         size_bytes;      /**< Memory footprint in bytes (16000 bytes) */
    const uint16_t*  waveform_lut;    /**< Pointer to Flash-resident uint16_t LUT */
} SonarProfileDescriptor_t;
#endif /* SONAR_PROFILES_H_ */

/**
 * @brief  Retrieves full descriptor for a given profile ID.
 * @param  id: Profile ID (LOW_FREQUENCY, BALANCED, or HIGH_FREQUENCY).
 * @return Pointer to const SonarProfileDescriptor_t, or NULL if invalid.
 */
const SonarProfileDescriptor_t* Sonar_GetProfile(SonarProfileId_t id);

/**
 * @brief  Retrieves pointer to Flash-resident 12-bit DAC lookup table.
 * @param  id: Profile ID.
 * @return Const pointer to uint16_t array of 8,000 samples.
 */
const uint16_t* Sonar_GetProfileLUT(SonarProfileId_t id);

/**
 * @brief  Retrieves sample count for a given profile (always 8000 in v1).
 */
uint16_t Sonar_GetProfileSampleCount(SonarProfileId_t id);

/**
 * @brief  Retrieves human-readable string name of profile.
 */
const char* Sonar_GetProfileName(SonarProfileId_t id);

/**
 * @brief  Retrieves total count of available profiles (3).
 */
uint32_t Sonar_GetProfileCount(void);

/**
 * @brief  Validates that all profile LUTs pass static integrity checks.
 * @return true if all tables are non-NULL and 8000 samples long.
 */
bool Sonar_ValidateLUTIntegrity(void);

#ifdef __cplusplus
}
#endif

#endif /* SONAR_LUT_H_ */
